### ISSUE TITLE
Criar uma função static para dar refresh na imagem 

### ISSUE THREAD

**Issue by martchellop** [GCyrillo/Photocyl#2]
Como ainda não descobrimos um modo de alterar as imagens automaticamente, sugiro uma função static que possa ser chamada de qualquer lugar para dar refresh na janela principal

**Comment by BrunoGomesCoelho** [comment]
Criei uma função refresh, basta que toda janela aberta use OpenAndWait() ou algo do tipo na hora de carregar a cena.
